### ISSUE TITLE
Key successPreviewDuration expected Integer but value was a java.lang.Double.  The default value 1 was returned.

### ISSUE THREAD

**Issue by Dallas62** [klippa-app/react-native-klippa-scanner-sdk#5]
Hi,

When I run the exemple code:
https://github.com/klippa-app/react-native-klippa-scanner-sdk#usage

With the following configuration on `Success` (value you provide):
```js
        // After capture, show a checkmark preview with this success message, instead of a preview of the image.
        Success: {message: "Success!", previewDuration: 0.3},
```

I get the following issue on Android
```
02-16 10:47:19.034  5793  5793 W Bundle  : Key successPreviewDuration expected Integer but value was a java.lang.Double.  The default value 1 was returned.
02-16 10:47:19.035  5793  5793 W Bundle  : Attempt to cast generated internal exception:
02-16 10:47:19.035  5793  5793 W Bundle  : java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
02-16 10:47:19.035  5793  5793 W Bundle  :      at android.os.BaseBundle.getInt(BaseBundle.java:1041)
02-16 10:47:19.035  5793  5793 W Bundle  :      at android.content.Intent.getIntExtra(Intent.java:7835)
02-16 10:47:19.035  5793  5793 W Bundle  :      at com.klippa.scanner.KlippaScanner.onCreate(Unknown Source:838)
02-16 10:47:19.035  5793  5793 W Bundle  :      at android.app.Activity.performCreate(Activity.java:7802)
02-16 10:47:19.035  5793  5793 W Bundle  :      at android.app.Activity.performCreate(Activity.java:7791)
02-16 10:47:19.035  5793  5793 W Bundle  :      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
02-16 10:47:19.035  5793  5793 W Bundle  :      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
02-16 10:47:19.035  5793  5793 W Bundle  :      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
02-16 10:47:19.035  5793  5793 W Bundle  :      at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
02-16 10:47:19.035  5793  5793 W Bundle  :      at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
02-16 10:47:19.035  5793  5793 W Bundle  :      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
02-16 10:47:19.035  5793  5793 W Bundle  :      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
02-16 10:47:19.035  5793  5793 W Bundle  :      at android.os.Handler.dispatchMessage(Handler.java:107)
02-16 10:47:19.035  5793  5793 W Bundle  :      at android.os.Looper.loop(Looper.java:214)
02-16 10:47:19.035  5793  5793 W Bundle  :      at android.app.ActivityThread.main(ActivityThread.java:7356)
02-16 10:47:19.035  5793  5793 W Bundle  :      at java.lang.reflect.Method.invoke(Native Method)
02-16 10:47:19.035  5793  5793 W Bundle  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
02-16 10:47:19.035  5793  5793 W Bundle  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

Regards,

**Comment by MarkDoggen** [comment]
Hi,

Thanks for reporting this! Can be fixed by updating the klippaScannerVersion in build.gradle to version 1.3.4

**Comment by jerbob92** [comment]
Or updating the package to 0.1.3 :)
