### ISSUE TITLE
Android Issue - Issue with preview of retaken photo.

### ISSUE THREAD

**Issue by pstarzycki** [klippa-app/react-native-klippa-scanner-sdk#75]
Platform:

Android Studio Koala
Gradle: 6.9
Gradle Plugin: 4.1.0
Java: openjdk 14.0.1 2020-04-14
RN version: 0.68.2
RN scanner SDK version: 0.3.2
Klippa SDK version 1.0.0

The problem is that when you make a photo, press on trash bin, retake photo and then want to preview it, the app crash without any error printed in debugger (only sentry catches it).
Is it known issue that has been fixed - and upgrade of dependencies will fix it?
I'm aware that my setup should be upgraded, but I'm waiting for a good moment with it. 

Stack Trace from sentry:
```
java.lang.IllegalArgumentException: Navigation action/destination se.bfree.bflow:id/action_klippaCameraFragment_to_klippaPreviewFragment cannot be found from the current destination NavGraph(se.bfree.bflow:id/nav_graph) startDestination={Destination(se.bfree.bflow:id/klippaCameraFragment) label=klippa_fragment_camera class=com.klippa.scanner.closed.screens.camera.view.KlippaCameraFragment}
    at androidx.navigation.NavController.navigate(NavController.kt:1540)
    at androidx.navigation.NavController.navigate(NavController.kt:1472)
    at androidx.navigation.NavController.navigate(NavController.kt:1454)
    at androidx.navigation.NavController.navigate(NavController.kt:1437)
    at com.klippa.scanner.closed.screens.camera.view.KlippaCameraFragment.handleThumbnailClicked
    at com.klippa.scanner.closed.screens.camera.view.KlippaCameraFragment.setClickListeners$lambda$13
    at com.klippa.scanner.closed.screens.camera.view.KlippaCameraFragment.lambda$aAN3im4nxClv_3E5LQje85gRUYU
    at com.klippa.scanner.closed.screens.camera.view.-$$Lambda$KlippaCameraFragment$aAN3im4nxClv_3E5LQje85gRUYU.onClick
    at android.view.View.performClick(View.java:7751)
    at android.view.View.performClickInternal(View.java:7728)
    at android.view.View.access$3700(View.java:859)
    at android.view.View$PerformClick.run(View.java:29148)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:210)
    at android.os.Looper.loop(Looper.java:299)
    at android.app.ActivityThread.main(ActivityThread.java:8337)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
```
crash demo:

https://github.com/user-attachments/assets/04838ad6-7051-4b1a-bd9f-04fd83f3a3c5

https://drive.google.com/file/d/1JnnokYjpAbBCz9mRYDw-OjxfOh6rMzG0/view?usp=sharing

**Comment by RobinFarmer** [comment]
Hi @pstarzycki ,

Thanks for reporting this; yes this was actually just fixed with Android Scanner SDK version `3.1.8`. 
If you bump your react-native-klippa-scanner-sdk version to `0.4.3` or higher it should be fixed.

In case you still run into problems with the newest version feel free to reopen this issue.
